baseURL = "https://vignette.agency"
copyright = "&copy;2020 Vignette: Natalie Boruvka and Karl Rogers"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
googleAnalytics = "UA-170489089-1"
languageCode = "en-US"
theme = "hugo-split-theme"
title = "Vignette Content Agency"
[params]
author = "Natalie Boruvka"
description = "Vignette is a photographic content agency specialising in decor and lifestyle editorials. We create bespoke imagery to elevate brands."
favicon = "favicon.ico"
shareImage = "images/social.jpg"
[params.custom.css]
enable = true
[params.visual.image]
enable = true
file = "images/background.jpg"
position = "center center"
[params.visual.video]
enable = false
file = "videos/background.mp4"
mute = true
[[params.links]]
[params.links.list1]
heading = "Network"
[[params.links.list1.link]]
text = "Karl Rogers karlrogers.co.za"
url = "https://karlrogers.co.za/"
[[params.links.list1.link]]
text = "Natalie Boruvka natalieboruvka.com"
url = "https://natalieboruvka.com/"
[[params.links]]
[params.links.list2]
heading = "Social"
[[params.links.list2.link]]
text = "Instagram @vignette.sa"
url = "https://instagram.com/vignette.sa/"
[[params.links]]
[params.links.list3]
heading = "Connect"
[[params.links.list3.link]]
text = "+27 72 606 9392"
url = "#"
[[params.links.list3.link]]
text = "Contact Form"
url = "contact/"
